version: 2
updates:

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: "Europe/Paris"
  open-pull-requests-limit: 10
  reviewers:
    - "Meyclem"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: "Europe/Paris"
  reviewers:
    - "Meyclem"
