name: "Dependabot AutoMerge"
description: "Allows to automatically review and merge Dependabot's pull requests."
inputs:
  github-token:
    description: "A Githib Personal Access Token"
    required: true
  npm-disallowlist:
    description: "A list of NPM packages you want to handle differently"
    required: false
  gha-disallowlist:
    description: "A list of Github Actions you want to handle differently"
    required: false
  reviewers:
    description: "The reviewers that will be ask the review if needed"
    required: false
runs:
  using: 'node16'
  main: 'build/index.js'
