name: "Dependabot AutoMerge"
description: "Allows to automatically review and merge Dependabot's pull requests."
inputs:
  github-token:
    description: "A Githib Personal Access Token"
    required: true
  blacklist:
    description: "A list of NPM packages you want to handle differently"
    required: false
runs:
  using: 'node16'
  main: 'build/index.js'
